fix: Qt 6.11 compatibility for QCompleter include
Fixes the following build failure on Arch:

```
src/widgets/dsearchcombobox.cpp:46:49: error: invalid use of incomplete type ‘class QCompleter’
```

(cherry picked from commit ed98b1cda3e8f08f8095d1229f403d7c5ee0a12b)